POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Unite Summit",
  "details": "The biggest event of South America",
  "slug": "unite-summit",
  "maximunAttendees": 12500
}
